# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CAO-2-sW322WrLXKaZpBs2F6GzExl0T
"""

import streamlit as st
import pandas as pd
import requests
import matplotlib.pyplot as plt

def obtener_datos_api(api_url):
    """Función que realiza la petición a la API y devuelve un DataFrame."""
    response = requests.get(api_url)
    if response.status_code == 200:
        data = response.json()
        return pd.DataFrame(data)
    else:
        st.error('Error al obtener los datos de la API')
        return None
api_url = 'https://jsonplaceholder.typicode.com/posts'

df = obtener_datos_api(api_url)
if df is not None:

    st.title("Datos obtenidos de la API")
    st.write("Primeras 5 filas del DataFrame:")
    st.write(df.head())


    columnas = st.multiselect('Selecciona las columnas a visualizar', df.columns.tolist(), default=df.columns.tolist())
    df_seleccionado = df[columnas]
    st.write("Datos seleccionados:")
    st.write(df_seleccionado)


    id_filtro = st.slider('Filtrar por ID (entre 1 y 100)', 1, 100, 50)
    df_filtrado = df[df['id'] <= id_filtro]
    st.write(f"Datos donde ID <= {id_filtro}:")
    st.write(df_filtrado)


    st.title("Visualización de datos")
    fig, ax = plt.subplots()
    df['userId'].value_counts().sort_index().plot(kind='bar', ax=ax)
    ax.set_title('Conteo de User ID')
    ax.set_xlabel('User ID')
    ax.set_ylabel('Frecuencia')
    st.pyplot(fig)